---
title: "Single Cell Analysis with Seurat using singleCellTK Package"
author: "`r params$authors`"
date: "`r format(Sys.time(), '%B %d, %Y')`"
params:
  subtitle: !r NULL
  authors: !r NULL
  sce: !r NULL
  biological.group: !r NULL
  phenotype.groups: !r NULL
  selected.markers: !r NULL
  clustering.resolution: 0.8
  variable.features: 2000
  pc.count: 50
  outputPath: !r NULL
  showSession: TRUE
  pdf: TRUE
  jackStraw: FALSE
  data: !r NULL
  sigPC: 10
output:
  html_document:
    toc: yes
    toc_float: yes
    number_sections: yes
    theme: cosmo
    code_folding: hide
    self_contained: false
  pdf_document:
    toc: yes
subtitle: "`r params$subtitle`"
editor_options:
  chunk_output_type: console
---

```{r parameters_setup, include = TRUE, message=FALSE, warning=FALSE, echo=FALSE}
#Loading required libraries
library(Seurat)
library(dplyr)
library(cowplot)
library(RColorBrewer)
library(ggplot2)
library(knitr)
library(kableExtra)
library(SingleCellExperiment)
library(scater)
library(gridExtra)
library(grid)
library(ggpubr)
library(patchwork)
library(singleCellTK)

#Setting up parameters and loading data
group <- params$biological.group
selected_phenotypes <- params$phenotype.groups
Pre_selected_markers <- params$selected.markers
seurat.selected.resolution <- as.numeric(params$clustering.resolution)
seurat.selected.features.numbers <- as.numeric(params$variable.features)
initial.PC.numbers <- as.numeric(params$pc.count)
sampleNames <- unique(colData(data)[[group]])
outputPath <- params$outputPath
showSession <- params$showSession
pdf <- params$pdf
data <- params$data
significant_PC <- params$sigPC

numCells <- ncol(data)
numFeatures <- nrow(data)
numSamples <- length(sampleNames)

# Knitr Global Options
dev <- ifelse(isTRUE(pdf), c("png"), c("png", "pdf"))
opts_chunk$set(
  echo = TRUE,
  cache = FALSE,
  cache.lazy = FALSE,
  cache.comments = FALSE,
  fig.align = "center",
  fig.keep = "all",
  dev = dev,
  warning = FALSE
)
```


# Seurat Results

## Selected Resolution {.tabset .tabset-fade}
A final resolution of **`r seurat.selected.resolution`** was selected for downstream clustering that better reflects the input data.

<!-- Clustering -->
```{r, echo=FALSE, results='hide', warning=FALSE, message=FALSE}
runClustering <- TRUE
minResolution <- 0.8
maxResolution <- 0.8
numClusters <- 10 #remove this later
showClusterDesc <- FALSE

resClustering <- knitr::knit_child('reportSeuratClustering.Rmd', quiet = TRUE)
```

```{r, echo=FALSE, results='asis', warning=FALSE, message=FALSE}
cat(resClustering, sep = '\n')
```

<!-- Pre-selected Markers -->
```{r preselected markers, echo=FALSE, results='asis', warning=FALSE, message=FALSE}
runMarkerSelection <- FALSE
plotMarkerSelection <- TRUE
numClusters <- 1
selectedOption <- paste0("Seurat_louvain_Resolution", seurat.selected.resolution)
titleMarkerPlots <- "Plot Selected Features"
countFeatures <- length(Pre_selected_markers)
res <- knitr::knit_child('reportSeuratMarkerSelection.Rmd', quiet = TRUE)
cat(res, sep = '\n')
```

<!-- Marker Selection (Clusters) -->
```{r markerSelection Clusters, echo=FALSE, results='asis', warning=FALSE, message=FALSE}
runMarkerSelection <- TRUE
plotMarkerSelection <- TRUE
numClusters <- length(unique(colData(data)[[paste0("Seurat_louvain_Resolution", seurat.selected.resolution)]]))
selectedOption <- paste0("Seurat_louvain_Resolution", seurat.selected.resolution)
groupTitle <- "Clusters"
titleMarkerPlots <- "Gene Plots of Top Markers by Clusters"
countFeatures <- 10
res <- knitr::knit_child('reportSeuratMarkerSelection.Rmd', quiet = TRUE)
cat(res, sep = '\n')
```

<!-- Marker Selection (Group) -->
```{r, echo=FALSE, results='asis', warning=FALSE, message=FALSE}
runMarkerSelection <- TRUE
plotMarkerSelection <- TRUE
numClusters <- length(unique(colData(data)[[group]]))
selectedOption <- group
groupTitle <- group
titleMarkerPlots <- paste0("Gene Plots of Top Markers by Group: ", group)
countFeatures <- 10
res <- knitr::knit_child('reportSeuratMarkerSelection.Rmd', quiet = TRUE)
cat(res, sep = '\n')
```

# Session Information
```{r session, eval = showSession, echo = showSession}
sessionInfo()
```

