---
title: "Music results"
author: "Amulya Shastry"
date: "2022-10-27"
params:
  object: object
  analysisName: analysisName
  analysisType: analysisType
  heatmapTitle: heatmapTitle
  bulkData: bulkData, 
  analysisName: r! NULL,
  analysisType: c("EstCellProp","PreGroupedClustProp","SingleCellClust"), 
  markers: r!NULL, 
  clusters: clusters, # not a default -- user input 
  samples: "sampleID", #sample is the default and not sampleID but keeping this as sampleID for testing purpose
  preClusterlist: NULL,
  DEmarkers: NULL,
  groups: NULL, 
  selectCt: NULL, #same as select.ct
  cellSize: NULL, #same as cell_size 
  ctCov: FALSE, #same as ctCov
  verbose: TRUE,
  iterMax: 1000, #same as iter.max 
  nu: 1e-04,
  eps: 0.01,
  centered: FALSE,
  normalize: FALSE,
  nonZero: TRUE
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r MuSiC_params}
sce <- params$object
analysisName<-params$analysisName
analysisType<-params$analysisType
heatmapTitle<-params$heatmapTitle
```


<!-- Music Run -->

```{r, echo=FALSE, results='asis', warning=FALSE, message=FALSE}
showSession <- FALSE
musicRun <- knitr::knit_child('reportMusicRun.Rmd', quiet = TRUE, envir = environment())
```

<!-- Music Results -->

```{r, echo=FALSE, results='asis', warning=FALSE, message=FALSE}
showSession <- FALSE
musicResults <- knitr::knit_child('reportMusicResults.Rmd', quiet = TRUE, envir = environment())
```



```{r, echo=FALSE, results='asis', warning=FALSE, message=FALSE}
cat(musicRun, sep = '\n')
cat(musicResults, sep = '\n')
```



 

```{r, echo=FALSE}
showSession <- params$showSession
```



```{r, results='asis', eval=showSession, echo=FALSE}
cat("# Session Information\n\n")
```


```{r, results='markup', eval=showSession, echo=showSession}
sessionInfo()
```




