app <- ShinyDriver$new("../../", seed = 20)
app$snapshotInit("seurat")

app$setInputs(uploadChoice = "example")
app$setInputs(selectExampleData = "fluidigm_pollen")
app$setInputs(addExampleImport = "click")
app$setInputs(uploadData = "click")
app$setInputs(navbar = "Seurat")
app$setInputs(normalize_button = "click")
app$setInputs(scale_button = "click")
app$setInputs(activePanelSelectSeurat = "Highly Variable Genes")
app$setInputs(find_hvg_button = "click")
Sys.sleep(10)
app$snapshot(items = list(output = c("plot_hvg", "hvg_output")), screenshot = TRUE)